import React from "react";
import styled from "styled-components";

function Header(props) {
  Triangle.defaultProps = {
    theme: {
      screenWidth: window.innerWidth,
      screenHeight: window.innerHeight,
    },
  };

  return (
    <MainContainer>
      <ImageBackground />
      <Triangle />
      <TextContainer>
        {window.innerWidth <= 899 ? (
          <h1>
            Johan Linol <br /> Dev Web Junior
          </h1>
        ) : (
          <h1>
            Johan Linol <br /> Développeur Web Junior
          </h1>
        )}
        <LogoContainer>
          <img src="/img/mint.png" alt="" />
          <img src="/img/react.png" alt="" />
          <img src="/img/javascript.png" alt="" />
        </LogoContainer>
      </TextContainer>
    </MainContainer>
  );
}

export default Header;

const MainContainer = styled.div`
  width: 100vw;
  height: 100vh;
  position: relative;
`;

const ImageBackground = styled.div`
  width: 100%;
  height: 100%;
  // background: linear-gradient(to left bottom, rgb(236, 72, 153), rgb(239, 68, 68), rgb(234, 179, 8));
  z-index: 1;
  position: relative;
  animation: color-change-2x 2s linear infinite alternate both;
  @keyframes color-change-2x {
    0% {
      background: rgb(236, 72, 153);
    }
    50% {
      background: rgb(239, 68, 68);
    }
    100% {
      background: rgb(234, 179, 8);
    }
  }
`;

const Triangle = styled.div`
  position: absolute;
  top: 0;
  right: 0;
  width: 0;
  height: 0;
  border-style: solid;
  border-width: 0 ${(props) => props.theme.screenWidth}px ${(props) => props.theme.screenHeight}px 0;
  border-color: transparent black transparent transparent;
  z-index: 2;
`;

const TextContainer = styled.div`
  position: absolute;
  top: 27%;
  left: 10%;
  z-index: 3;
  width: 80%;
  height: auto;
  max-height: 40%;
  display: flex;
  flex-direction: column;
  align-items: center;

  > h1 {
    font-size: 4rem;
    text-align: center;
  }

  @media only screen and (max-width: 899px) {
    top: 35%;
    > h1 {
      font-size: 2.5rem;
    }
  }
`;

const LogoContainer = styled.div`
  width: 100%;
  height: 50%;
  display: flex;
  flex-direction: row;
  align-items: center;
  justify-content: space-around;
  > img {
    height: 200px;
  }

  @media only screen and (max-width: 899px) {
    > img {
      height: 10vh;
      margin-top: 2rem;
    }
  }
`;

/* ----------------------------------------------
 * Animation Generated by Animista
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */
